[tool.poetry]
name = "nodestream"
version = "0.1.0"
description = ""
authors = ["Zach Probst <zprobst@resilientvitality.com>"]
readme = "README.md"

[tool.isort]
profile = "black"

[tool.poetry.dependencies]
python = "^3.11"
pyyaml = "^6.0"
jmespath = "^1.0.1"
jq = "^1.4.1"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.4.2"
mkdocs-material = "^9.1.8"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
black = "^23.3.0"
pyhamcrest = "^2.0.4"
isort = "^5.12.0"
pytest-cov = "^4.0.0"
pytest-asyncio = "^0.21.0"
pytest-mock = "^3.10.0"

[tool.poetry.plugins]
pytest11 = { nodestram = "nodestream.test" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
